### PR TITLE
WIP: Signature 4 support

### PR DESCRIPTION
**Pull request by Jc2k**
As of e75d433 I am able to create buckets, list bucket contents, upload and then download files using s3cmd. I've done multipart uploads of > 20 parts happily with it. I have also had it working with other internal s3 stuff, including ranged requests.

This is still very WIP - and only targets a subset of the sig4 signing styles (e.g. no chunked uploads).

It's definitely not ready to merge, but i have no prior experience with clojure and I don't know quite how bad this is 😱, so early feedback would be good.

There are also some questions for the maintainers.

 * `:uri` is replaced. Bucket path rewriting happens before the authorization code runs. This was invalidating the signatures. So i create an `:orig-uri` before this happens. Is there a better way?

* You can only read `:body` once. For testing I have just read `:body` as bytes into `:contents` and then attached a stream to `:body` that wraps `:contents`. This doesn't seem ideal. I can probably use `x-amz-content-sha256` to avoid shaing the body myself - it looks like its required for sig4 - but I haven't gone down that route yet. In that case I'd wrap `:body` in something that would error later on if it was closed and the final sha didn't match the header. I don't know if that is achievable in pithos, though. (E.g. might it just be too late...). Again, can you suggest a better way?

### CODE REVIEW

**Comment by Jc2k** [comment]
Hey, thanks for replying. I've thrown in a `starts-with?` on it.

I think i'll remove `:content` next and just use `x-amz-content-sha256` as the payload hash in my canonical request generation - later on i'll look how to validate the body against x-amz-content-sha256. I suspect i'll need to get more familiar with pithos internals to handle that.

**Comment by Jc2k** [comment]
The `:content` change has been reverted. I now rely on `x-amz-content-sha256` to generate a body payload canonical request and wrap `:body` in a adaptor that will throw when it is closed if the payload didn't match the signature.

This seems to work in so much as validation passes and the upload is allowed to happen, but i still need to do an integration test where a valid canonical request / signature is generated but then the payload isn't uploaded or is different - i'm unsure if it will make a mess in the data store?

I'm going to attempt a similar approach with the streaming uploads next (`STREAMING-AWS4-HMAC-SHA256-PAYLOAD`).

**Comment by Antauri** [comment]
Can this be merged please? I have a few fixes for this WIP (on validate4 merging authorization with the tenant from the keystore). We've tested the WIP and seems that all operations work (from create-bucket, list-bucket, delete-bucket and all the copy/delete operations).

**Comment by Jc2k** [comment]
I have a few fixes pending too (they need cherry picking from another branch). We’ve been running this branch for a while with moloch streaming packing capture data to it without issue, so would be good to get it finally merged.

**Comment by Jc2k** [comment]
^ Thats the biggest outstanding patch I had; sounds like you might have a similar one yourself. 

It looks like I started to implement STREAMING-AWS4-HMAC-SHA256-PAYLOAD too, but thats not ready to push.

**Comment by Antauri** [comment]
More along the lines of merging the authorization with the "tenant" resolved from keystore. It was just simpler. Note that I'm a Clojure newbie (have opened the Clojure In Action book for a week now). The below merge fixed the "aws s3api list-buckets" operation (while all others worked). Without the tenant merging the CQL query would fail with WHERE tenant = nil.

```
(defn validate4
  [keystore request]
  (let [
    authorization (parse-authorization request)
    secret-key (get (get keystore (get authorization :access-key)) :secret)
    tenant-from-keystore (get (get keystore (get authorization :access-key)) :tenant)
    is-valid-signature (is-signed-by? request authorization secret-key)]
       (debug "request" request)
       (debug "authorization" (get keystore (get authorization :access-key)))
       (debug "secret" secret-key)
       (debug "is-valid-sig" is-valid-signature)
       (debug "tenant-from-keystore" tenant-from-keystore)
    (cond
      is-valid-signature
      (merge (update-in authorization [:memberof] concat ["authenticated-users" "anonymous"])
             {:tenant tenant-from-keystore})
      :else
      anonymous)
    ))
```

Fact is that his project (in comparison to Minio, Ladon or other implementations) relies on C* for which we have extensive monitoring (and experience). On our side, if the project is still maintained (as in someone doing daily merges of PRs) I would like to contribute back with some code.

@Jc2k you should probably remove the "WIP" prefix if you're confident with it. I know I am, cause I integrated your changes by-hand in our own fork.

@brutasse or @pyr is someone still doing maintenance (daily PR merges) on this project or should we look into forks of it (eg. jc2k's)

**Comment by Jc2k** [comment]
Thanks @pyr!

**Comment by Antauri** [comment]
Woohoo! I salute this merge!

**Pull request merged**
